import { Product } from './store';

export const categories = [
  'Electronics',
  'Clothing',
  'Home & Garden',
  'Sports',
  'Books',
  'Health & Beauty',
  'Toys',
  'Automotive',
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
    category: 'Electronics',
    rating: 4.8,
    reviewCount: 1247,
    description: 'High-quality wireless headphones with noise cancellation and premium sound quality.',
    slug: 'premium-wireless-headphones',
    featured: true,
    sale: true,
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    price: 29.99,
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg',
    category: 'Clothing',
    rating: 4.5,
    reviewCount: 892,
    description: 'Comfortable and sustainable organic cotton t-shirt available in multiple colors.',
    slug: 'organic-cotton-t-shirt',
    featured: true,
  },
  {
    id: '3',
    name: 'Smart Fitness Watch',
    price: 199.99,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg',
    category: 'Electronics',
    rating: 4.6,
    reviewCount: 2156,
    description: 'Advanced fitness tracking with heart rate monitoring and GPS functionality.',
    slug: 'smart-fitness-watch',
    featured: true,
  },
  {
    id: '4',
    name: 'Ceramic Plant Pot Set',
    price: 49.99,
    image: 'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg',
    category: 'Home & Garden',
    rating: 4.3,
    reviewCount: 564,
    description: 'Beautiful set of ceramic plant pots perfect for indoor gardening.',
    slug: 'ceramic-plant-pot-set',
  },
  {
    id: '5',
    name: 'Professional Camera Lens',
    price: 899.99,
    originalPrice: 1199.99,
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg',
    category: 'Electronics',
    rating: 4.9,
    reviewCount: 423,
    description: 'High-performance camera lens for professional photography.',
    slug: 'professional-camera-lens',
    sale: true,
  },
  {
    id: '6',
    name: 'Yoga Mat Premium',
    price: 59.99,
    image: 'https://images.pexels.com/photos/317155/pexels-photo-317155.jpeg',
    category: 'Sports',
    rating: 4.7,
    reviewCount: 1834,
    description: 'Non-slip premium yoga mat made from eco-friendly materials.',
    slug: 'yoga-mat-premium',
    featured: true,
  },
  {
    id: '7',
    name: 'Leather Backpack',
    price: 129.99,
    image: 'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg',
    category: 'Clothing',
    rating: 4.4,
    reviewCount: 756,
    description: 'Stylish and durable leather backpack perfect for work and travel.',
    slug: 'leather-backpack',
  },
  {
    id: '8',
    name: 'Bluetooth Speaker',
    price: 79.99,
    image: 'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg',
    category: 'Electronics',
    rating: 4.5,
    reviewCount: 1298,
    description: 'Portable Bluetooth speaker with excellent sound quality and long battery life.',
    slug: 'bluetooth-speaker',
  },
];

export const featuredProducts = products.filter(product => product.featured);
export const saleProducts = products.filter(product => product.sale);

export const mockOrders = [
  {
    id: 'ORD-001',
    date: '2024-01-15',
    status: 'delivered',
    total: 399.98,
    items: [
      { name: 'Premium Wireless Headphones', quantity: 1, price: 299.99 },
      { name: 'Bluetooth Speaker', quantity: 1, price: 79.99 },
    ],
  },
  {
    id: 'ORD-002',
    date: '2024-01-10',
    status: 'shipped',
    total: 89.98,
    items: [
      { name: 'Organic Cotton T-Shirt', quantity: 2, price: 29.99 },
      { name: 'Yoga Mat Premium', quantity: 1, price: 59.99 },
    ],
  },
];