import { Product } from "./type";

export const categories = [
  "Electronics",
  "Clothing",
  "Home & Garden",
  "Sports",
  "Books",
  "Health & Beauty",
  "Toys",
  "Automotive",
];

export const products: Product[] = [
  {
    name: "Premium Wireless Headphones",
    price: 299.99,
    originalPrice: 399.99,
    category: {
      name: "Electronics",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 1247,
    description:
      "High-quality wireless headphones with noise cancellation and premium sound quality.",
    slug: "premium-wireless-headphones",
    featured: true,
    sale: true,
    city: "Vapi",
    images: [
      "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
    ],
    isActive: true,
    stock: 10,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    images: [
      "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg",
    ],
    category: {
      name: "Clothing",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 892,
    description:
      "Comfortable and sustainable organic cotton t-shirt available in multiple colors.",
    slug: "organic-cotton-t-shirt",
    featured: true,
    city: "Vapi",
    isActive: true,
    stock: 10,
    originalPrice: 59.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Smart Fitness Watch",
    price: 199.99,
    images: [
      "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
    ],
    category: {
      name: "Electronics",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 2156,
    description:
      "Advanced fitness tracking with heart rate monitoring and GPS functionality.",
    slug: "smart-fitness-watch",
    featured: true,
    city: "Vapi",
    isActive: true,
    stock: 10,
    originalPrice: 249.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Ceramic Plant Pot Set",
    price: 49.99,
    images: [
      "https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg",
    ],
    category: {
      name: "Home & Garden",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 564,
    description:
      "Beautiful set of ceramic plant pots perfect for indoor gardening.",
    slug: "ceramic-plant-pot-set",
    city: "Vapi",
    isActive: true,
    stock: 10,
    featured: true,
    originalPrice: 99.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Professional Camera Lens",
    price: 899.99,
    originalPrice: 1199.99,
    images: ["https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg"],
    category: {
      name: "Electronics",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 423,
    description: "High-performance camera lens for professional photography.",
    slug: "professional-camera-lens",
    sale: true,
    city: "Vapi",
    isActive: true,
    stock: 10,
    featured: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Yoga Mat Premium",
    price: 59.99,
    images: [
      "https://images.pexels.com/photos/317155/pexels-photo-317155.jpeg",
    ],
    category: {
      name: "Sports",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 1834,
    description: "Non-slip premium yoga mat made from eco-friendly materials.",
    slug: "yoga-mat-premium",
    featured: true,
    city: "Vapi",
    isActive: true,
    stock: 10,
    originalPrice: 119.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Leather Backpack",
    price: 129.99,
    images: [
      "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg",
    ],
    category: {
      name: "Clothing",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 756,
    description:
      "Stylish and durable leather backpack perfect for work and travel.",
    slug: "leather-backpack",
    city: "Vapi",
    isActive: true,
    stock: 10,
    featured: true,
    originalPrice: 159.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
  {
    name: "Bluetooth Speaker",
    price: 79.99,
    images: [
      "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg",
    ],
    category: {
      name: "Electronics",
      xata_createdat: "",
      xata_id: "rec_d1f59ji4rg3c8402bk3g",
      xata_updatedat: "",
      xata_version: 0,
    },
    reviewCount: 1298,
    description:
      "Portable Bluetooth speaker with excellent sound quality and long battery life.",
    slug: "bluetooth-speaker",
    city: "Vapi",
    isActive: true,
    stock: 10,
    featured: true,
    originalPrice: 99.99,
    sale: true,
    totalStar: 900,
    xata_createdat: "",
    xata_id: "rec_d1f59ji4rg3c8402bk3g",
    xata_updatedat: "",
    xata_version: 0,
  },
];

export const featuredProducts = products.filter((product) => product.featured);
export const saleProducts = products.filter((product) => product.sale);

export const mockOrders = [
  {
    id: "ORD-001",
    date: "2024-01-15",
    status: "delivered",
    total: 399.98,
    items: [
      { name: "Premium Wireless Headphones", quantity: 1, price: 299.99 },
      { name: "Bluetooth Speaker", quantity: 1, price: 79.99 },
    ],
  },
  {
    id: "ORD-002",
    date: "2024-01-10",
    status: "shipped",
    total: 89.98,
    items: [
      { name: "Organic Cotton T-Shirt", quantity: 2, price: 29.99 },
      { name: "Yoga Mat Premium", quantity: 1, price: 59.99 },
    ],
  },
];
